runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  PROJECT_ID: 'utility-subset-367815'
  GOOGLE_APPLICATION_CREDENTIALS: 'key.json'

runtime_config:
  python_version: 3.7

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
